### ISSUE TITLE
适配多点输入设备和Pen输入

### ISSUE THREAD

**Issue by syfxlin** [syfxlin/graffiti-board#1]
用PointerEvent可以监听鼠标，触摸，Pen输入，同时可以监听压力。

**Comment by zhaouv** [comment]
我注意到你网站里的demo比这个仓库多了
```js
    if (e.buttons === 32) {
      config.type = "eraser";
    }
    if (
      e.pointerType === "pen" &&
      config.type === "eraser" &&
      e.buttons === 1
    ) {
      config.type = "pen";
    }
```
以支持pen,  
问下你是否还有继续开发这个库的计划.  
我正在制作vscode的手写输入的插件, 搜索到了几个库, 其中这个库的完成度最高. 正在修改这个库作为webview来输入  
如果有开发计划的话我会提个issue写一些希望做的修改

**Comment by syfxlin** [comment]
@zhaouv 这个库最初是为了给 xkeditor 添加涂鸦板功能开发出来的，功能方面基本已经满足，所以应该不会进行功能的性的更新了，不过我目前正在开发 xkeditor-next，后续应该会把这个项目改成模块的形式。
